[package]
name = "snake"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slither-core = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
crossbeam-deque = { workspace = true }
governor = { workspace = true }
dashmap = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
scraper = { workspace = true }
xxhash-rust = { workspace = true }
